### ISSUE TITLE
[XIRR] The return of the follow instruction is not a % is an amount

### ISSUE THREAD

**Issue by Jlopez04** [ebradyjobory/finance.js#37]
I execute with the version     "financejs": "^4.1.0",

the follow instruction 

console.log(finance.XIRR([-91000.00, 75000.00, -11500.00, -3500.00, 75000.00, -86720.00, -2500.00, -8000.00, 75000.00, -2500.00, -480.00, 75000.00, -1040.00],[ new Date(2018, 10, 29 ),  new Date(2018, 10, 29 ),  new Date(2018, 11, 12 ),  new Date(2018, 11, 22 ),  new Date(2018, 11, 22 ),  new Date(2018, 11, 29 ),  new Date(2018, 12, 3 ),  new Date(2018, 12, 10 ),  new Date(2018, 12, 10 ),  new Date(2018, 12, 20 ),  new Date(2018, 12, 22 ),  new Date(2018, 12, 27 ),  new Date(2019, 1, 10 )],0));

and gives me the follow amount as a result

83206612.79

The idea as I understan os this function is return e % not an amount .

Someone knows, what could be the problem?

**Comment by sharddith** [comment]
@Jlopez04  The **value is %**, you can validate the same by using the same values in **Excel and using the "XIRR" function**. 
You also need to keep in mind that **Months in java script is 0-11**; therefore date such as  new **Date(2018, 12, 27 )**, will roll over and **will be taken as Jan 27 2018**

Hope this helps.

While checking on excel do keep in mind:  **new Date(2018, 10, 29 ) is Nov 29 2018**

**Comment by Jlopez04** [comment]
Thanks sharddith I have resolved the issue basically is not an issue the number is correct .
